name: routine_maker_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.7
  go_router: ^5.1.0
  grpc: ^3.0.2
  protobuf: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  go_router_builder: ^1.0.14

flutter:
  uses-material-design: true
