name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  grpc: ^3.0.2
  grpc_gen:
    path: ../grpc_gen

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
